apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-bwev
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-bwev
    app.kubernetes.io/part-of: test-app-docj
  name: test-component-bwev
  namespace: build-e2e-cobr-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: test-component-bwev
    weight: null
status: {}
